# Site Settings
title: Rajesh Saharan
email: 16072000rajesh@gmail.com
description: >
  A guide to getting start front-end HTML,CSS, javascript (js) or back-end php, Nodejs, or basic ethical Hacking blog. 
baseurl: ""
url: "http://rajeshsaharan.github.io"
twitter_username: Rajestic
github_username:  Rajeshsaharan
# Build Settings
sass:
  sass_dir: _sass

include: ['_pages']
kramdown:
  input: GFM


# SEO stuff
google_author: ""
google_site_verification: ""
bing_webmastertools_id: ""

- scope:
      path: "_categories"
    values:
      layout: "category"
